### PR TITLE
Add EFI Bios

### PR DESCRIPTION
**Pull request by KnKay**
Hi all,

we neede dto manipulate the BIOS, as well as the EFI Disk. 

This was not possible. After merge of: https://github.com/Telmate/proxmox-api-go/pull/116 this can be done using packer!

### CODE REVIEW

**Comment by carlpett** [comment]
Hey @KnKay, thanks for the PR! It looks like you might have an issue with your branch, though? It contains all the commits of the repo?

**Comment by KnKay** [comment]
Hi @carlpett, you are right. I just added the changes. Merged the main of the plugin. I hope this fixes any issues. 
The teste, somehow still will fail, as the MR on the API is not yet done!

**Comment by carlpett** [comment]
Ah, now I think I see the problem - you need to change the target branch to `main`, instead of `master`.
Also, we'll need to wait for the the upstream PR to be merged so you can incorporate it into this one.

**Comment by KnKay** [comment]
@carlpett Okay, now I get it. Was a bit confused about the master and main branches. 
I changed it. Let's wait, as the MR we rely on the api side is open as well!

**Comment by sylviamoss** [comment]
Hi @KnKay, could sign the CLA so that we can merge this one when it's ready?

**Comment by KnKay** [comment]
Hi Sylvia, 
I signed it. I some how used 2 names... I am KnKay and Kay Richter. Can I make something to get this solved as well? 
Do I need to rewrite the history simply?

**Pull request closed without merging**
