### PR TITLE
Docs: import partials

### PR DESCRIPTION
**Pull request by mabeett**
Transfers documentation from mdx files to sourcecode.

This PR just affects documentation

### CODE REVIEW

**Comment by mabeett** [comment]
Next steps:
- final docs consistency and style.

**Comment by sebastian-de** [comment]
Thanks for this! I was playing around with the same idea a few months ago. In the end I gave up because of https://github.com/hashicorp/packer-plugin-sdk/issues/74
Since the Proxmox builder heavily relies on nested structs I never found a way to make the docs render like I wanted them to. Did you find a way to work around this limitation?

**Comment by mabeett** [comment]
Hello @sebastian-de !

> Did you find a way to work around this limitation?

Well, I am quite unsure :-(. This is one of the reasons for considering this PR a Draft.

I tried to follow the [ebs builder from packer-plugin-amazon](https://github.com/hashicorp/packer-plugin-amazon/blob/main/docs/builders/ebs.mdx?plain=1#L50) as @lbajolet-hashicorp [suggested](https://github.com/hashicorp/packer-plugin-proxmox/pull/195#issuecomment-1567526579) me in #195 .

**Comment by mabeett** [comment]
There might be space for improvements or corrections based on general criteria.
Let me know if something apply.
I've been using [mdtohtml](https://github.com/gomarkdown/mdtohtml) when i tried to get html files with links, but it seems not being enough.

**Comment by mabeett** [comment]
> Hello @sebastian-de !
> 
> > Did you find a way to work around this limitation?
> 
> Well, I am quite unsure :-(. ~This is one of the reasons for considering this PR a Draft.~
> 

I've just searched for matches between references in the mdx file and  `mapstructure` in the builders' structs in the go files.  
At some point some text had no builder `mapstructure`, so I searched in the dependencies, with the match I added the corresponding `@include` in the mdx file.

I tried something like (I don't remember exactly):

```golang
type Config struct {
[...]
	// @include 'packer-plugin-sdk/multistep/commonsteps/HTTPConfig.mdx'
	commonsteps.HTTPConfig `mapstructure:",squash"`
```
And the output in the final mdx was expanded, but I did not see this pattern in the aws EBS builder

**Comment by mabeett** [comment]
Hello @lbajolet-hashicorp ,
Do you have any comment regarding this PR?

I also see there is also another PR (#219) which might force rework this one.

( cc @nywilken)

**Comment by nywilken** [comment]
> Hello @lbajolet-hashicorp , Do you have any comment regarding this PR?
> 
> I also see there is also another PR (#219) which might force rework this one.
> 
> ( cc @nywilken)

@mabeett apologies we have been heads down. I'll circle back after updating the other plugins to use the integrations PR. I will like to get this merged and then rebase the #219 on to it.

**Review by nywilken — APPROVED** [review]
These changes look good to me. I see you found the partials that are embedded into the SDK struct-markdown command for ISOConfig and CDConfig so that all looks good. Running a diff against the generated doc preview and that was is already on main I see a few positional changes and additions for new config options that were added. 

Thanks for making this change.

**Pull request merged**
