### PR TITLE
Verify template_name and vm_name per proxmox requirements

### LINKED ISSUE #14: Underscore not allowed in template name
#### Overview of the Issue

When using an underscore in the `template_name` configuration option, building of the image will fail with:

`Error updating template: 400 Parameter verification failed.`

With commit https://github.com/hashicorp/packer-plugin-proxmox/commit/66dd01bcb964f5a95192af7861dfcb65713fc47e a check for spaces in the template name was introduced, but an underscore is an invalid character as well. This is shown in the Proxmox web UI when trying to use it in a template name:

proxmox_template_name

#### Reproduction Steps

Set a name for the template with an underscore in it, for example:
```
template_name        = "centos_stream-8"
```
### Plugin and Packer version

Packer v1.7.2

### PR DESCRIPTION
**Pull request by karliemeads**
### Proposed Change:
Validate vm_name and template name for the proxmox builder to ensure they meet the proxmox naming scheme. This uses the same regex that proxmox uses in its webui.

### Background:
In proxmox, the name of templates and virtual machines must be valid DNS names. This is validated in the proxmox webui here: https://git.proxmox.com/?p=proxmox-widget-toolkit.git;a=blob;f=src/Utils.js;hb=e2ecec942fa19505cbb53d4b8eba6f356ea35b88#l1148
image

A valid DNS name is defined here:
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#:~:text=DNS%20names%20can%20contain%20only,components%20of%20domain%20style%20names.

Closes #14

### CODE REVIEW

**Comment by azr** [comment]
Hello @carlpett, are you able to review/merge this one ? Is the code owners file constructed correctly ?

**Comment by carlpett** [comment]
Hey @azr,
Look like Github isn't adding me as a reviewer automatically... Code owners requires write access to the repo, and since I also don't seem to be able to merge PRs, I think that's the issue. Can you add me?

**Review by carlpett — APPROVED** [review]
Looks good to me! Thanks!

**Comment by karliemeads** [comment]
Added tests. Address'd default blank template_name. Re-requesting review.

**Review by SwampDragons — APPROVED** [review]

**Comment by SwampDragons** [comment]
@carlpett We should probably figure out how to transfer ownership of this plugin to the Proxmox org, so you all can manage it fully. Do you all have a github presence we can move the repo to?

**Comment by carlpett** [comment]
I'm not affiliated with Proxmox at all, this plugin was the typical "scratch an itch" thing :)
But I've reached out to Proxmox-the-company and asked for their thoughts!

**Comment by nywilken** [comment]
> I'm not affiliated with Proxmox at all, this plugin was the typical "scratch an itch" thing :)
> But I've reached out to Proxmox-the-company and asked for their thoughts!

Thanks @carlpett much appreciated. Keep us posted on what you hear back. 

FWIW the suggest transfer path is as follows: 

- [ ] Maintainer forks the plugin repository from hashicorp/packer-plugin-${name}.
- [ ] Maintainer modifies fork settings to allow issue creation on fork.
- [ ] Maintainer works to update the release configuration on the repository to test a single pre-release. 
- [ ] HashiCorp posts section in the README that the main repository is now be maintained in the fork.
- [ ] HashiCorp archives the original repository indicating that it is no longer maintained by HashiCorp.
- [ ] HashiCorp works with maintainer to transfer any open issues. 

GitHub does offer the ability to transfer full ownership of a repository, which is also an option, but it does require some temporary configuration of write access in the target org and removal of settings on the main repo before the transfer. We can go that route as well if necessary.

**Pull request merged**
